package kitchenexpress;

import java.awt.*;
import java.io.*;
import java.util.logging.*;
import javax.swing.*;

/**
 * Este JFrame se encarga de crear los archivos del sistema en la ruta especificada.
 * @author José Polo
 * @author Wilson Tovar
 */
public class Inicio extends javax.swing.JFrame {

    private File StockFile;
    static File PedidosEntregados, PedidosParaEntregar, PlatosFile, PedidosFile, FacturasFile, IngredientesFile;
    private JFileChooser chooser;
    static Principal ventana1;
    static Cocina ventanaCocina;
    static Menú ventanaMenú;
    static Admin ventanaAdmin;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        Ini();
    }

    /**
     * Inicializar JFrame.
     */
    private void Ini() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/Logo7059.png"))); // Icono
        this.setMinimumSize(new Dimension(850, 550));
        this.setLocationRelativeTo(null);
        chooser = new JFileChooser();

        chooser.setDialogTitle("Path del sistema de Kitchen Express");
        //Modifica el chooser para que solo seleccione directorios
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //Quita todos los filtros de los archivos del chooser
        chooser.setAcceptAllFileFilterUsed(false);
        /*Establece como el directorio seleccionado por defecto, el directorio por defecto 
        del FileChooser para evitar posteriores errorres de directorio nulo.
         */
        chooser.setSelectedFile(chooser.getCurrentDirectory());

        //Escribe el directorio por defecto en el TextField(fileroute)
        filesroute.setText(chooser.getSelectedFile().toString() + "\\");
        filesroute.setEditable(false);

        advertencia.setLocationRelativeTo(null);
        advertencia.setAlwaysOnTop(true);
        advertencia.setUndecorated(true);
        AColor.setToolTipText("¡Pulse para ocultar!");

        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        advertencia = new javax.swing.JFrame();
        AColor = new javax.swing.JPanel();
        Atitle = new javax.swing.JLabel();
        Aface = new javax.swing.JLabel();
        AsubTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        filesroute = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        select_start = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();

        advertencia.setTitle("¡ERROR! ");
        advertencia.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/Logo7059.png")));
        advertencia.setResizable(false);
        advertencia.setSize(new java.awt.Dimension(800, 190));

        AColor.setBackground(new java.awt.Color(249, 211, 55));
        AColor.setToolTipText("");
        AColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AColor.setPreferredSize(new java.awt.Dimension(800, 250));
        AColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AColorMousePressed(evt);
            }
        });
        AColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AColorKeyPressed(evt);
            }
        });

        Atitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        Atitle.setForeground(new java.awt.Color(255, 255, 255));
        Atitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Atitle.setText("¡No ha seleccionado ningún directorio!");

        Aface.setFont(new java.awt.Font("Calibri", 1, 100)); // NOI18N
        Aface.setForeground(new java.awt.Color(255, 255, 255));
        Aface.setText(":(");

        AsubTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        AsubTitle.setForeground(new java.awt.Color(255, 255, 255));
        AsubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AsubTitle.setText("Se usará el directorio por defecto.");

        javax.swing.GroupLayout AColorLayout = new javax.swing.GroupLayout(AColor);
        AColor.setLayout(AColorLayout);
        AColorLayout.setHorizontalGroup(
            AColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Aface)
                .addGroup(AColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AColorLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(AsubTitle))
                    .addGroup(AColorLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Atitle)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        AColorLayout.setVerticalGroup(
            AColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AColorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(AColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Aface)
                    .addGroup(AColorLayout.createSequentialGroup()
                        .addComponent(Atitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AsubTitle)
                        .addGap(12, 12, 12)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout advertenciaLayout = new javax.swing.GroupLayout(advertencia.getContentPane());
        advertencia.getContentPane().setLayout(advertenciaLayout);
        advertenciaLayout.setHorizontalGroup(
            advertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advertenciaLayout.createSequentialGroup()
                .addComponent(AColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        advertenciaLayout.setVerticalGroup(
            advertenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AColor, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("¡Bienvenido a KitchenExpress!");
        setForeground(java.awt.Color.white);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 600));

        jPanel2.setBackground(new java.awt.Color(45, 108, 223));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Logo7059.png"))); // NOI18N
        jLabel2.setText("Logo");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kitchen Express");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );

        filesroute.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        filesroute.setToolTipText("Directorio de la carpeta del sistema");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido al sistema");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>A continuación seleccione la ruta donde se encuentra <br> \nla carpeta del sistema (KE_System) o donde ésta se creará:</html>");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel4.setText("Ruta:");

        select_start.setBackground(new java.awt.Color(255, 255, 255));
        select_start.setText("Seleccionar");
        select_start.setToolTipText("Seleccionar ruta");
        select_start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        select_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_startActionPerformed(evt);
            }
        });

        aceptar.setBackground(new java.awt.Color(255, 255, 255));
        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Aceptar terminado7070.png"))); // NOI18N
        aceptar.setToolTipText("Aceptar");
        aceptar.setAutoscrolls(true);
        aceptar.setBorderPainted(false);
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filesroute, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_start, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
            .addComponent(jLabel5)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filesroute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(select_start, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ventana de advertencia de errores / info.
     *
     * @param title Título de la ventana
     * @param subtitle Subtítulo de la ventana
     * @param color Color de la ventana
     * @param face
     */
    void advertencia(String title, String subtitle, Color color, String face) {
        Atitle.setText(title);
        AsubTitle.setText(subtitle);
        AColor.setBackground(color);
        Aface.setText(face);
        advertencia.setVisible(true);
    }

    /**
     * Cerrar ventana de inicio y continuar con los siguientes módulos.
     */
    private void CerrarYContinuar() {
        PedidosParaEntregar = verificarArchivo(StockFile, "PedidosParaEntregar", "txt");
        PedidosEntregados = verificarArchivo(StockFile, "PedidosEntregados", "txt");
        IngredientesFile = verificarArchivo(StockFile, "Ingredientes", "txt");
        PlatosFile = verificarArchivo(StockFile, "Platos", "txt");
        PedidosFile = verificarArchivo(StockFile, "Pedidos", "txt");
        FacturasFile = verificarArchivo(StockFile, "Facturas", "txt");

        if (PedidosParaEntregar != null && PlatosFile != null && PedidosFile != null && FacturasFile != null && IngredientesFile != null) {
            this.dispose();

            /**
             * Se inicializan aquí las ventanas del programa porque se necesitan
             * parámetros que solo se tendrán al cerrar la ventana actual
             */
            ventanaMenú = new Menú();
            ventanaMenú.setVisible(false);
            ventana1 = new Principal();
            ventana1.setVisible(true);

            /**
             * Se inicializa ventanaCocina aquí porque depende de datos de
             * ventana1 que se inicializa en la instrucción anterior
             */
            ventanaAdmin = new Admin();
            ventanaAdmin.setVisible(false);
            ventanaCocina = new Cocina();
            ventanaCocina.setVisible(false);

        } else {
            advertencia(
                    "¡Algo inesperado ha ocurrido con la creación de archivos!",
                    "Reinicie el programa y use otro directorio.",
                    Color.ORANGE,
                    ":|"
            );
        }
    }

    /**
     * Método para verificar si el archivo existe y generar uno nuevo si no
     * existe.
     *
     * @param dirArchivo Directorio donde se guardará el archivo.
     * @param nameArchivo Nombre del archivo.
     * @param fileType Tipo de archivo.
     * @return
     */
    File verificarArchivo(File dirArchivo, String nameArchivo, String fileType) {
        File archivo = new File(dirArchivo + "\\" + nameArchivo + "." + fileType);
        if (archivo.exists() == false) {
            try {
                archivo.createNewFile();
                System.out.println("INFO (Inicio) : " + archivo.getName() + " ha sido creado.");
            } catch (IOException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                return null;
            }
        } else {
            System.out.println("INFO (Inicio) : " + archivo.getName() + " ya existe.");
        }
        return archivo;
    }

    /**
     * Abrir el diálogo para seleccionar la ubicación de los archivos de KE.
     *
     * @param evt Click sobre el botón 'Seleccionar'.
     */
    private void select_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_startActionPerformed
        //Aquí se cierra la ventana de advertencia en caso de que el usuario haya olvidado cerrarla.
        if (advertencia.isVisible() == true) {
            advertencia.dispose();
        }
        int option = chooser.showOpenDialog(this); //Abre el filechooser y almacena como se cerró la ventana

        if (option == JFileChooser.APPROVE_OPTION) { //Procesa la información del filechooser
            filesroute.setText((chooser.getSelectedFile()).toString() + "\\");
        } else {
            advertencia(
                    "¡No ha seleccionado ningún directorio!",
                    "Se usará el directorio por defecto.",
                    new Color(249, 211, 55),
                    ":("
            );
        }
    }//GEN-LAST:event_select_startActionPerformed

    /**
     * Crear / Leer los archivos. Continuar con el sistema.
     *
     * @param evt Click sobre el ícono de aceptar.
     */
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        //Aquí se cierra la ventana de advertencia en caso de que el usuario haya olvidado cerrarla.
        if (advertencia.isVisible() == true) {
            advertencia.dispose();
        }

        StockFile = chooser.getSelectedFile();

        //Se comprueba si el directorio actual es KE_System
        if (StockFile.getName().equals("KE_System")) {
            //StockFile = new File(StockFile.getAbsolutePath().substring(0, StockFile.getAbsolutePath().length() - StockFile.getName().length() - 1));
            //System.out.println(StockFile.getPath());
            CerrarYContinuar();
        } else {
            StockFile = new File(StockFile + "\\KE_System");
            //Comprueba si el directorio existe en la ruta especificada
            if (StockFile.isDirectory() == false) {
                try {
                    //Intenta crear el directorio
                    StockFile.mkdir();
                    System.out.println("INFO (Inicio) : " + StockFile.toString() + " directory has been created");
                    CerrarYContinuar();
                } catch (Exception e) {
                    advertencia(
                            "¡No se puede crear el directorio aquí!",
                            "Porfavor seleccione otra diferente.",
                            Color.RED,
                            "!"
                    );
                }
            } else {
                System.out.println("INFO (Inicio) : " + StockFile.toString() + " directory already exist");
                CerrarYContinuar();
            }
        }
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * Cerrar la ventana de advertencia.
     *
     * @param evt Se hace click sobre la ventana de la advertencia.
     */
    private void AColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AColorMousePressed
        advertencia.dispose();
    }//GEN-LAST:event_AColorMousePressed

    /**
     * Cerrar la ventana de advertencia.
     *
     * @param evt Se presiona cualquier tecla.
     */
    private void AColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AColorKeyPressed
        advertencia.dispose();
    }//GEN-LAST:event_AColorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            /*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             */
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AColor;
    private javax.swing.JLabel Aface;
    private javax.swing.JLabel AsubTitle;
    private javax.swing.JLabel Atitle;
    private javax.swing.JButton aceptar;
    private javax.swing.JFrame advertencia;
    private javax.swing.JTextField filesroute;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton select_start;
    // End of variables declaration//GEN-END:variables
}
