package kitchenexpress;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * JFrame principal, desde el cual se efectúan la mayoría de las tareas.
 *
 * @author José Polo
 * @author Wilson Tovar
 */
public class Principal extends javax.swing.JFrame {

    public int camarero = 1;

    /**
     * Creates new form Principal
     *
     */
    public Principal() {
        initComponents();
        Ini();
    }

    /**
     * Eliminar borde a un botón
     *
     * @param button Botón al que se le eliminarán los bordes.
     */
    static public void quitBorder(JButton button) {
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setFocusPainted(false);
        button.setOpaque(false);
    }

    /**
     * Inicializar JFrame.
     */
    private void Ini() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/Logo7059.png"))); // Icono
        quitBorder(this.menuButton);
        quitBorder(this.atrasButton);
        quitBorder(this.camarerosButton);
        quitBorder(this.cocinaButton);
        quitBorder(this.ordenesButton);
        quitBorder(this.notifButton);
        quitBorder(this.adminButton);
        quitBorder(this.adminKitchenButton);
        quitBorder(atrasButton1);

        this.setLocationRelativeTo(null);
        this.setLayout(null);
        camarerosFrame.setLocationRelativeTo(null);
        pedidosEntregarFrame.setLocationRelativeTo(null);
        this.setSize(new Dimension(850, 550));
        this.setResizable(false);
        camarerosFrame.setSize(new Dimension(850, 550));
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        camarerosFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        pedidosEntregarFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);

        //Llenar el combobox de los meseros
        camareroBox.removeAllItems();
        camareroBox.setToolTipText("Seleccione su ID de mesero");
        for (int i = 1; i < 5; i++) {
            camareroBox.addItem("Camarero " + i);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camarerosFrame = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        ordenesButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        notifButton = new javax.swing.JButton();
        atrasButton = new javax.swing.JButton();
        camareroBox = new javax.swing.JComboBox<>();
        pedidosEntregarFrame = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        atrasButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidosPorEntregar = new javax.swing.JTable();
        btnFacturar = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlistPedidosEntregados = new javax.swing.JList<>();
        ventanaFactura = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtCODIGO = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMESA = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtMESERO = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtFECHA = new javax.swing.JLabel();
        txtTIEMPO = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        camarerosButton = new javax.swing.JButton();
        cocinaButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        adminKitchenButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        camarerosFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        camarerosFrame.setTitle("Camarero - KE");
        camarerosFrame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/Logo7059.png")));
        camarerosFrame.setMinimumSize(new java.awt.Dimension(850, 550));
        camarerosFrame.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(45, 108, 223));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Logo7059.png"))); // NOI18N
        jLabel6.setText("Logo");

        jLabel12.setFont(new java.awt.Font("Source Sans Pro Light", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kitchen Express");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        menuButton.setBackground(new java.awt.Color(255, 255, 255));
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Menú-terminado.png"))); // NOI18N
        menuButton.setToolTipText("Menú");
        menuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuButton.setMaximumSize(new java.awt.Dimension(200, 200));
        menuButton.setMinimumSize(new java.awt.Dimension(200, 200));
        menuButton.setPreferredSize(new java.awt.Dimension(200, 200));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        ordenesButton.setBackground(new java.awt.Color(255, 255, 255));
        ordenesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Selección.png"))); // NOI18N
        ordenesButton.setToolTipText("Ordenes");
        ordenesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ordenesButton.setMaximumSize(new java.awt.Dimension(200, 200));
        ordenesButton.setMinimumSize(new java.awt.Dimension(200, 200));
        ordenesButton.setPreferredSize(new java.awt.Dimension(200, 200));
        ordenesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenesButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Menú");

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ordenes");

        notifButton.setBackground(new java.awt.Color(255, 255, 255));
        notifButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Campana-terminada_n.png"))); // NOI18N
        notifButton.setToolTipText("Notificaciones");
        notifButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notifButton.setMaximumSize(new java.awt.Dimension(50, 50));
        notifButton.setMinimumSize(new java.awt.Dimension(50, 50));
        notifButton.setPreferredSize(new java.awt.Dimension(50, 50));
        notifButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifButtonActionPerformed(evt);
            }
        });

        atrasButton.setBackground(new java.awt.Color(255, 255, 255));
        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Flecha5050.png"))); // NOI18N
        atrasButton.setToolTipText("Atrás");
        atrasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasButton.setMaximumSize(new java.awt.Dimension(50, 50));
        atrasButton.setMinimumSize(new java.awt.Dimension(50, 50));
        atrasButton.setPreferredSize(new java.awt.Dimension(50, 50));
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });

        camareroBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        camareroBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        camareroBox.setToolTipText("Seleccione el meresero");
        camareroBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                camareroBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(atrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notifButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ordenesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(camareroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(camareroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ordenesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notifButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atrasButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout camarerosFrameLayout = new javax.swing.GroupLayout(camarerosFrame.getContentPane());
        camarerosFrame.getContentPane().setLayout(camarerosFrameLayout);
        camarerosFrameLayout.setHorizontalGroup(
            camarerosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        camarerosFrameLayout.setVerticalGroup(
            camarerosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pedidosEntregarFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        pedidosEntregarFrame.setTitle("Pedidos por entregar - KE");
        pedidosEntregarFrame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/Logo7059.png")));
        pedidosEntregarFrame.setMinimumSize(new java.awt.Dimension(850, 550));
        pedidosEntregarFrame.setResizable(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setToolTipText("");
        jPanel6.setMaximumSize(new java.awt.Dimension(850, 550));
        jPanel6.setMinimumSize(new java.awt.Dimension(850, 550));
        jPanel6.setPreferredSize(new java.awt.Dimension(850, 550));

        jPanel7.setBackground(new java.awt.Color(45, 108, 223));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Logo7059.png"))); // NOI18N
        jLabel13.setText("Logo");

        jLabel14.setFont(new java.awt.Font("Source Sans Pro Light", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kitchen Express");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(48, 48, 48))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        atrasButton1.setBackground(new java.awt.Color(255, 255, 255));
        atrasButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Flecha5050.png"))); // NOI18N
        atrasButton1.setToolTipText("Atrás");
        atrasButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        atrasButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        atrasButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        atrasButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setText("Pedidos por entregar");

        tablaPedidosPorEntregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaPedidosPorEntregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Mesa", "Mesero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPedidosPorEntregar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaPedidosPorEntregar.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tablaPedidosPorEntregar);
        if (tablaPedidosPorEntregar.getColumnModel().getColumnCount() > 0) {
            tablaPedidosPorEntregar.getColumnModel().getColumn(0).setResizable(false);
            tablaPedidosPorEntregar.getColumnModel().getColumn(1).setResizable(false);
            tablaPedidosPorEntregar.getColumnModel().getColumn(2).setResizable(false);
        }

        btnFacturar.setText("Facturar");
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });

        btnEntregar.setText("Entregar");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mesas con pedidos por facturar (Mesa - Cod. Pedido)");

        jlistPedidosEntregados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlistPedidosEntregados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jlistPedidosEntregados);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jScrollPane3)
                                        .addComponent(jSeparator1))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(atrasButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFacturar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atrasButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pedidosEntregarFrameLayout = new javax.swing.GroupLayout(pedidosEntregarFrame.getContentPane());
        pedidosEntregarFrame.getContentPane().setLayout(pedidosEntregarFrameLayout);
        pedidosEntregarFrameLayout.setHorizontalGroup(
            pedidosEntregarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pedidosEntregarFrameLayout.setVerticalGroup(
            pedidosEntregarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ventanaFactura.setTitle("Factura - KE");
        ventanaFactura.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/Logo7059.png")));
        ventanaFactura.setMinimumSize(new java.awt.Dimension(424, 546));
        ventanaFactura.setResizable(false);

        jPanel8.setBackground(new java.awt.Color(45, 108, 223));

        jLabel16.setFont(new java.awt.Font("Source Sans Pro Light", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Factura");

        txtCODIGO.setFont(new java.awt.Font("Source Sans Pro Light", 0, 36)); // NOI18N
        txtCODIGO.setForeground(new java.awt.Color(255, 255, 255));
        txtCODIGO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCODIGO.setText("#COD");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCODIGO)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtCODIGO))
                .addGap(20, 20, 20))
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setText("Productos");

        tablaProd.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Prod", "Cant.", "Total"
            }
        ));
        jScrollPane2.setViewportView(tablaProd);

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setText("TOTAL");

        txtTOTAL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTOTAL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTOTAL.setText("$ 0.0");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Mesa:");

        txtMESA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMESA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMESA.setText("Mesa");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Mesero:");

        txtMESERO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMESERO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMESERO.setText("Mesero");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Fecha:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Tiempo:");

        txtFECHA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFECHA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtFECHA.setText("Fecha");

        txtTIEMPO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTIEMPO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTIEMPO.setText("Tiempo");

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Nota: Los aranceles son la suma del IVA(19%) y la propina(10%) por producto.");

        javax.swing.GroupLayout ventanaFacturaLayout = new javax.swing.GroupLayout(ventanaFactura.getContentPane());
        ventanaFactura.getContentPane().setLayout(ventanaFacturaLayout);
        ventanaFacturaLayout.setHorizontalGroup(
            ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ventanaFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaFacturaLayout.createSequentialGroup()
                        .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addGroup(ventanaFacturaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaFacturaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(ventanaFacturaLayout.createSequentialGroup()
                        .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMESERO)
                            .addComponent(txtMESA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFECHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTIEMPO, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaFacturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        ventanaFacturaLayout.setVerticalGroup(
            ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaFacturaLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaFacturaLayout.createSequentialGroup()
                        .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtMESA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtMESERO)))
                    .addGroup(ventanaFacturaLayout.createSequentialGroup()
                        .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtFECHA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventanaFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtTIEMPO))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kitchen Express");
        setResizable(false);
        setSize(new java.awt.Dimension(850, 550));

        jPanel1.setMinimumSize(new java.awt.Dimension(850, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(45, 108, 223));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Logo7059.png"))); // NOI18N
        jLabel2.setText("Logo");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kitchen Express");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(52, 52, 52))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        camarerosButton.setBackground(new java.awt.Color(255, 255, 255));
        camarerosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Bandeja.png"))); // NOI18N
        camarerosButton.setToolTipText("Camareros");
        camarerosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        camarerosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camarerosButtonActionPerformed(evt);
            }
        });

        cocinaButton.setBackground(new java.awt.Color(255, 255, 255));
        cocinaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Sombrero-de-cocina.png"))); // NOI18N
        cocinaButton.setToolTipText("Cocina");
        cocinaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cocinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocinaButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Camareros");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cocina");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Administrador");

        adminButton.setBackground(new java.awt.Color(255, 255, 255));
        adminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Admin.png"))); // NOI18N
        adminButton.setToolTipText("Administrador");
        adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        adminKitchenButton.setBackground(new java.awt.Color(255, 255, 255));
        adminKitchenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/AdminCocina.png"))); // NOI18N
        adminKitchenButton.setToolTipText("Jefe de Cocina");
        adminKitchenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminKitchenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminKitchenButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Jefe de Cocina");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(camarerosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cocinaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(adminKitchenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cocinaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(camarerosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminKitchenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))))
                .addGap(0, 113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Volver a la ventana Principal.
     *
     * @param evt Click sobre el botón Atrás.
     */
    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed
        camarerosFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_atrasButtonActionPerformed

    /**
     * Abrir ventana de camareros.
     *
     * @param evt Click sobre el botón de Camareros.
     */
    private void camarerosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camarerosButtonActionPerformed
        this.setVisible(false);
        camarerosFrame.setVisible(true);
    }//GEN-LAST:event_camarerosButtonActionPerformed

    /**
     * Abrir ventana de órdenes.
     *
     * @param evt Click sobre el botón de órdenes.
     */
    private void ordenesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenesButtonActionPerformed
        Inicio.ventanaMenú.Ordenes.setVisible(true);;
        this.camarerosFrame.setVisible(false);
    }//GEN-LAST:event_ordenesButtonActionPerformed

    /**
     * Abrir ventana de cocina.
     *
     * @param evt Click sobre el botón de Cocina.
     */
    private void cocinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocinaButtonActionPerformed
        this.setVisible(false);
        Inicio.ventanaCocina.setVisible(true);
    }//GEN-LAST:event_cocinaButtonActionPerformed

    /**
     * Abrir ventana de menú.
     *
     * @param evt Click sobre el botón Menú.
     */
    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        camarerosFrame.setVisible(false);
        Inicio.ventanaMenú.setVisible(true);
    }//GEN-LAST:event_menuButtonActionPerformed

    /**
     * Abrir ventana de administrador.
     *
     * @param evt Click sobre el boton Administrador
     */
    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        this.setVisible(false);
        Inicio.ventanaAdmin.setVisible(true);
        Inicio.ventanaAdmin.Ventas(); // Total de ventas
        Inicio.ventanaAdmin.mostrarVentas(0);
        Inicio.ventanaAdmin.calcularMesero(); // Mesero que más vendió
        Inicio.ventanaAdmin.IngredientesMásUtilizado(); // Ingredientes más y menos utilizados
        Inicio.ventanaAdmin.platoMasVendido(); // Plato que más se vendió en el día.
    }//GEN-LAST:event_adminButtonActionPerformed

    /**
     *
     * @param evt
     */
    private void adminKitchenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminKitchenButtonActionPerformed
        Inicio.ventanaCocina.administradorCocinaFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminKitchenButtonActionPerformed

    /**
     * Al presionar el botón de la campanita.
     *
     * @param evt Click sobre el botón de la campanita.
     */
    private void notifButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifButtonActionPerformed
        pedidosEntregarFrame.setVisible(true);
        camarerosFrame.setVisible(false);
    }//GEN-LAST:event_notifButtonActionPerformed

    private void atrasButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButton1ActionPerformed
        pedidosEntregarFrame.setVisible(false);
        camarerosFrame.setVisible(true);
    }//GEN-LAST:event_atrasButton1ActionPerformed

    /**
     * Agregar pedido a la lista de entregados.
     *
     * @param evt
     */
    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaPedidosPorEntregar.getModel();

        if (modelo.getRowCount() > 0 && !(tablaPedidosPorEntregar.getSelectedRow() < 0)) {
            int i = tablaPedidosPorEntregar.getSelectedRow();

            Pedido Buscar = Inicio.ventanaCocina.PedidosParaEntrega;
            Pedido ant = null;

            while (Buscar != null && String.valueOf(Buscar.cod).equals(modelo.getValueAt(i, 0).toString()) == false) {
                ant = Buscar;
                Buscar = Buscar.link;
            }

            if (Inicio.ventanaCocina.PedidosEntregados == null) {
                Inicio.ventanaCocina.PedidosEntregados = new Pedido();
            }

            Pedido nuevoPedido = new Pedido(Buscar.tiempo);
            nuevoPedido.cod = Buscar.cod;
            nuevoPedido.Platos = Buscar.Platos;
            nuevoPedido.camarero = Buscar.camarero;
            nuevoPedido.mesa = Buscar.mesa;
            nuevoPedido.valortotal = Buscar.valortotal;
            Inicio.ventanaCocina.PedidosEntregados = Inicio.ventanaCocina.PedidosEntregados.addPedido(camarerosFrame, nuevoPedido); // Agregar pedido a la lista

            if (ant == null) {
                Inicio.ventanaCocina.PedidosParaEntrega = Inicio.ventanaCocina.PedidosParaEntrega.link;
            } else {
                ant.link = Buscar.link;
            }

            //modelo.removeRow(i);
            actualizarTablaPedidosPorEntregar(Inicio.ventanaCocina.PedidosParaEntrega);

            //Actualiza lista de pedidos por entregar en cocina
            if (Inicio.ventanaCocina.PedidosParaEntrega == null) {
                Inicio.ventanaCocina.PedidosParaEntrega = new Pedido();
                //Inicio.ventanaCocina.PedidosParaEntregarList.removeAll();
                Inicio.ventanaCocina.PedidosParaEntregarList.setModel(new DefaultListModel());
            } else {
                Inicio.ventanaCocina.PedidosParaEntrega.toJListByCod(Inicio.ventanaCocina.PedidosParaEntregarList);
            }

            //Guarda el archivo de pedidos a entregar
            Inicio.ventanaCocina.PedidosParaEntrega.toFile(camarerosFrame, Inicio.PedidosParaEntregar);
            //Guarda el archivo de pedidos entregados
            Inicio.ventanaCocina.PedidosEntregados.toFile(camarerosFrame, Inicio.PedidosEntregados);
            //Carga las mesas con pedidos entregados en la lista de las mismas en notificaciones
            Inicio.ventanaCocina.PedidosEntregados.toJListByCamarero(jlistPedidosEntregados, camarero);

        } else { // Si no seleccionó ningún pedido o no hay pedidos por entregar
            JOptionPane.showMessageDialog(pedidosEntregarFrame, "No ha seleccionado ningún pedido para entregar.", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEntregarActionPerformed

    /**
     * Facturar orden.
     *
     * @param evt Click sobre el boton Facturar.
     */
    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        if (jlistPedidosEntregados.getSelectedIndex() >= 0) {
            int elem = Integer.parseInt(jlistPedidosEntregados.getSelectedValue().substring(5, jlistPedidosEntregados.getSelectedValue().length()));
            Pedido Buscar = Inicio.ventanaCocina.PedidosEntregados;
            Pedido ant = null;

            //Busca el elemento seleccionado en la lista
            while (Buscar.cod != elem) {
                ant = Buscar;
                Buscar = Buscar.link;
            }

            Factura nuevaFactura = new Factura(Buscar);

            //Se añade la factura a la lista de facturas
            if (Inicio.ventanaCocina.Facturas == null) {
                Inicio.ventanaCocina.Facturas = new Factura();
            }
            Inicio.ventanaCocina.Facturas = Inicio.ventanaCocina.Facturas.addFactura(nuevaFactura);

            //Borra el pedido de la lista de pedidos por facturar
            if (ant == null) {
                Inicio.ventanaCocina.PedidosEntregados = Inicio.ventanaCocina.PedidosEntregados.link;
                if (Inicio.ventanaCocina.PedidosEntregados == null) {
                    Inicio.ventanaCocina.PedidosEntregados = new Pedido();
                    /*
                    * En vista de que no funciona esta instrucción 
                    * (jlistPedidosEntregados.removeAll();) para remover 
                    * todos los elementos de la lista se cambiará el modelo
                     */
                    jlistPedidosEntregados.setModel(new DefaultListModel());
                } else {
                    Inicio.ventanaCocina.PedidosEntregados.toJListByCamarero(jlistPedidosEntregados, camarero);
                }
            } else {
                ant.link = Buscar.link;
                Inicio.ventanaCocina.PedidosEntregados.toJListByCamarero(jlistPedidosEntregados, camarero);
            }

            //Actualiza pedidos entregados
            Inicio.ventanaCocina.PedidosEntregados.toFile(pedidosEntregarFrame, Inicio.PedidosEntregados);

            mostrarFactura(nuevaFactura);

            Inicio.ventanaCocina.Facturas.toFile(camarerosFrame, Inicio.FacturasFile);
            // TODO Corregir error al generar archivo de facturas
        }

    }//GEN-LAST:event_btnFacturarActionPerformed

    /**
     *
     * @param evt
     */
    private void camareroBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_camareroBoxItemStateChanged
        if (Inicio.ventanaCocina != null) {
            actualizarTablaPedidosPorEntregar(Inicio.ventanaCocina.PedidosParaEntrega);
            //Carga los pedidos del camarero respectivo en las notificaciones
            camarero = camareroBox.getSelectedIndex() + 1;
            Inicio.ventanaCocina.PedidosEntregados.toJListByCamarero(jlistPedidosEntregados, camarero);
            //Carga los pedidos de la mesa respectiva en su respectiva lista
            Inicio.ventanaCocina.Pedidos.toJListByMesa(Inicio.ventanaMenú.JListPedidosGenerados, 5 * (camarero - 1) + 1);
        }
        Inicio.ventanaMenú.mesaBox.removeAllItems();
        switch (camareroBox.getSelectedIndex() + 1) {
            case 1:
                for (int i = 1; i <= 5; i++) {
                    Inicio.ventanaMenú.mesaBox.addItem("Mesa_" + i);
                }
                break;
            case 2:
                for (int i = 6; i <= 10; i++) {
                    Inicio.ventanaMenú.mesaBox.addItem("Mesa_" + i);
                }
                break;
            case 3:
                for (int i = 11; i <= 15; i++) {
                    Inicio.ventanaMenú.mesaBox.addItem("Mesa_" + i);
                }
                break;
            case 4:
                for (int i = 16; i <= 20; i++) {
                    Inicio.ventanaMenú.mesaBox.addItem("Mesa_" + i);
                }
                break;

        }
    }//GEN-LAST:event_camareroBoxItemStateChanged

    /**
     * Mostrar factura.
     *
     * @param factura Factura que será mostrada.
     */
    public void mostrarFactura(Factura factura) {
        ventanaFactura.setLocationRelativeTo(null);
        ventanaFactura.setVisible(true);

        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        modelo.addColumn("Código");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Total");
        modelo.addColumn("Arandelas");

        tablaProd.setModel(modelo);

        tablaProd.getColumnModel().getColumn(1).setPreferredWidth(180);
        tablaProd.getColumnModel().getColumn(1).setResizable(false);

        PlatoPedido p = factura.platos;
        while (p != null) {
            modelo.addRow(new Object[]{p.cod, p.nombre, p.cant, p.value * p.cant, p.cant * p.value * 0.29});
            p = p.link;
        }

        txtMESA.setText(factura.mesa + "");
        txtMESERO.setText(factura.camarero + "");
        txtTOTAL.setText("$ " + factura.total);
        txtCODIGO.setText("#" + factura.cod);
        txtFECHA.setText(factura.fecha_exp);
        txtTIEMPO.setText(String.valueOf(factura.tiempo) + " seg.");
    }

    /**
     * Mostrar notificación de pedidos.
     */
    public void mostrarNotificacion() {
        notifButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Campana-terminada.png")));
    }

    /**
     * Ocultar notificación.
     */
    public void ocultarNotificacion() {
        notifButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kitchenexpress/Icons/Campana-terminada_n.png")));
    }

    /**
     * Actualizar la tabla de pedidos por entregar.
     *
     * @param PedidosEntrega es la lista de pedidos que se usará para actualizar
     * la tabla tablaPedidosPorEntregar
     */
    public void actualizarTablaPedidosPorEntregar(Pedido PedidosEntrega) {
        //System.out.println("Actualizando tabla de pedidos por entregar...");

        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }

        };
        tablaPedidosPorEntregar.setModel(modelo);
        modelo.addColumn("Cod");
        modelo.addColumn("Mesa");
        modelo.addColumn("Camarero");

        Pedido p = PedidosEntrega;
        boolean notif = false;

        if (p != null && p.camarero != 0) {
            while (p != null) {
                //System.out.println("Agregando fila");
                if (p.camarero == camarero) {
                    modelo.addRow(new Object[]{p.cod, p.mesa, p.camarero});
                    if (notif == false) {
                        notif = true;
                    }
                }
                p = p.link;
            }
        }
        // Si hay pedidos por entregar, mostrar notificación 
        if (notif) {
            mostrarNotificacion();
        } else {
            ocultarNotificacion();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            /*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             */
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton adminKitchenButton;
    private javax.swing.JButton atrasButton;
    private javax.swing.JButton atrasButton1;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnFacturar;
    public javax.swing.JComboBox<String> camareroBox;
    private javax.swing.JButton camarerosButton;
    public javax.swing.JFrame camarerosFrame;
    private javax.swing.JButton cocinaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JList<String> jlistPedidosEntregados;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton notifButton;
    private javax.swing.JButton ordenesButton;
    public javax.swing.JFrame pedidosEntregarFrame;
    private javax.swing.JTable tablaPedidosPorEntregar;
    private javax.swing.JTable tablaProd;
    private javax.swing.JLabel txtCODIGO;
    private javax.swing.JLabel txtFECHA;
    private javax.swing.JLabel txtMESA;
    private javax.swing.JLabel txtMESERO;
    private javax.swing.JLabel txtTIEMPO;
    private javax.swing.JLabel txtTOTAL;
    private javax.swing.JDialog ventanaFactura;
    // End of variables declaration//GEN-END:variables
}
